version: "3.9"

volumes:
  nginx-shared:

services:
  config-nginx:
    image: nginx:1.20-alpine
    env_file:
      - .env
    ports:
      - "${NGINX_HOST_PORT}:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - nginx-shared:${DOCKER_NGINX_VOLUME_ROOT}
    depends_on:
      - config-web
    networks:
      - safenetwork
    # network_mode: host
  config-db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    command: -p 5433
    networks:
      - safenetwork
  config-web:
    build: .
    tty: true
    volumes:
      - nginx-shared:${DOCKER_NGINX_VOLUME_ROOT}
    env_file:
      - .env
    depends_on:
      - config-db
    networks:
      - safenetwork

networks:
  safenetwork:
    name: safe_network
